[package]
name = "dotatlas" # atlas was taken, of course
version = "0.1.0"
authors = ["voxelstack <voxelstack@gmail.com>"]
edition = "2021"

[lib]
path = "src/dotatlas/lib.rs"
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1.7"
js-sys = "0.3.64"
rayon = "1.7.0"
wasm-bindgen = "0.2.87"
wasm-bindgen-rayon = "1.0.3"

[dependencies.web-sys]
version = "0.3.64"
features = [
    "Window",
    "OffscreenCanvas",
    "OffscreenCanvasRenderingContext2d",
    "console",
]

[dev-dependencies]
wasm-bindgen-test = "0.3.37"
