[package]
name = "dotatlas" # atlas was taken, of course
version = "0.1.0"
authors = ["voxelstack <voxelstack@gmail.com>"]
edition = "2021"

[lib]
path = "src/dotatlas/lib.rs"
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.87"
