[package]
name = "atlas-client"
version = "0.1.0"
authors = ["voxelstack <voxelstack@gmail.com>"]
edition = "2021"
description = "Friendly client to interact with atlas-server."
repository = "https://github.com/voxelstack/dotme"
license-file = "../../../LICENSE"

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
atlas-comms = { path = "../comms" }
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"

[dependencies.web-sys]
version = "0.3.64"
features = [
    "console",
    "Worker",
]

[dev-dependencies]
wasm-bindgen-test = "0.3.37"
