[package]
name = "atlas-client"
version = "0.1.0"
authors = ["voxelstack <voxelstack@gmail.com>"]
edition = "2021"
description = "Friendly client to interact with atlas-server."
repository = "https://github.com/voxelstack/dotme"
license-file = "../../../LICENSE"

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
atlas-comms = { path = "../comms" }
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.87"

[dev-dependencies]
wasm-bindgen-test = "0.3.37"
