[package]
name = "atlas-server"
version = "0.1.0"
authors = ["voxelstack <voxelstack@gmail.com>"]
edition = "2021"
description = "The world's most over-the-top background image generator."
repository = "https://github.com/voxelstack/dotme"
license-file = "../../../LICENSE"

[lib]
crate-type = ["cdylib"]

[dependencies]
atlas-comms = { path = "../comms" }
console_error_panic_hook = "0.1.7"
js-sys = "0.3.64"
log = "0.4.19"
rayon = "1.7.0"
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
wasm-bindgen-rayon = "1.0.3"

[dependencies.tokio]
version = "1.28.2"
features = [
    "sync"
]

[dependencies.web-sys]
version = "0.3.64"
features = [
    "DedicatedWorkerGlobalScope",
]

[dev-dependencies]
wasm-bindgen-test = "0.3.37"

[features]
loggers = ["atlas-comms/loggers"]
verification = ["atlas-comms/verification"]
