[package]
name = "atlas-comms"
version = "0.1.0"
authors = ["voxelstack <voxelstack@gmail.com>"]
edition = "2021"
description = "Common code for atlas server/client communication."
repository = "https://github.com/voxelstack/dotme"
license-file = "../../../LICENSE"

[lib]
path = "lib.rs"

[dependencies]
wasm-bindgen = "0.2.87"
