[package]
name = "atlas-comms"
version = "0.1.0"
authors = ["voxelstack <voxelstack@gmail.com>"]
edition = "2021"
description = "Common code for atlas server/client communication."
repository = "https://github.com/voxelstack/dotme"
license-file = "../../../LICENSE"

[dependencies]
async-trait = "0.1.68"
atlas-comms-derive = { path = "../comms_derive" }
console_error_panic_hook = "0.1.7"
console_log = { version = "1.0.0", optional = true }
fern = { version = "0.6.2", optional = true }
humantime = {version = "2.1.0", optional = true }
js-sys = "0.3.64"
log = "0.4.19"
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"

[dependencies.tokio]
version = "1.28.2"
features = [
    "sync"
]

[dependencies.web-sys]
version = "0.3.64"
features = [
    "console",
    "DedicatedWorkerGlobalScope",
    "MessageChannel",
    "MessagePort",
    "OffscreenCanvas",
    "Worker",
]

[dev-dependencies]
wasm-bindgen-test = "0.3.37"

[features]
loggers = ["dep:console_log", "dep:fern", "dep:humantime"]
